import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@audit/db';

export const runtime = 'nodejs';

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ runId: string }> }
) {
  try {
    const { runId } = await context.params;

    // Serve pre-generated PDF from database (generated by worker)
    const pdfKey = `runs/${runId}/report.pdf`;
    const storedFile = await prisma.storedFile.findUnique({ where: { key: pdfKey } });

    if (storedFile) {
      const buffer = Buffer.from(storedFile.data, 'base64');
      const cleanTarget = (await prisma.auditRun.findUnique({ where: { id: runId }, select: { target: true } }))
        ?.target?.replace(/^https?:\/\//, '').replace(/\/$/, '').replace(/[^a-z0-9]/gi, '-') || runId;

      return new NextResponse(buffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="firon-audit-${cleanTarget}.pdf"`,
        },
      });
    }

    // PDF not generated yet — return error
    return NextResponse.json(
      { error: 'PDF report not ready yet. Please wait for the audit to complete and try again.' },
      { status: 404 }
    );
  } catch (error: any) {
    console.error('PDF serve error:', error?.message);
    return NextResponse.json(
      { error: 'Failed to serve PDF', details: error?.message },
      { status: 500 }
    );
  }
}
